# Generated by Django 5.1.5 on 2025-01-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification_token_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur système'), ('DIRECTOR', 'Direction'), ('DIRECTOR HR', 'Directeur RH'), ('STAFF', 'Personnel administratif'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Étudiant'), ('PARENT', 'Parent'), ('LIBRARIAN', 'Bibliothécaire'), ('ACCOUNTANT', 'Comptabilité'), ('STOREKEEPER', 'Magasinier')], max_length=20),
        ),
    ]
