# Generated by Django 5.1.5 on 2025-01-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'verbose_name': 'Document'},
        ),
    ]
