# Generated by Django 5.1.5 on 2025-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("inventory_number", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("performed_by", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("minimum_quantity", models.PositiveIntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
