# Generated by Django 5.1.5 on 2025-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                ("target_audience", models.CharField(max_length=50)),
                ("priority", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("read_date", models.DateTimeField(blank=True, null=True)),
                (
                    "attachments",
                    models.FileField(
                        blank=True, null=True, upload_to="message_attachments/"
                    ),
                ),
            ],
        ),
    ]
